### ISSUE TITLE
Error: npm install appium-uiautomator2-driver

### ISSUE THREAD

**Issue by JJunM** [appium/appium-uiautomator2-driver#361]
**Warning:**
- npm ver:  6.13.4
- node.js ver: 10.16.0
- cmd> npm install appium-uiautomator2-driver

An error occurs during installation. Please check the attached image.

![aa](https://user-images.githubusercontent.com/46311868/72044549-57d35500-32f7-11ea-8d46-e51dd37fe7b9.png)

These issues are not tracked. Please create new issues in the main Appium
repository: https://github.com/appium/appium/issues/new

**Comment by imurchie** [comment]
Those are just warnings, and unless you are using functionality that require web sockets, it should not be a problem of any sort.

Further, the two optional dependencies just improve performance (see [note here](https://github.com/websockets/ws#opt-in-for-performance-and-spec-compliance)). We do not include them because they both require local building of native code, which is both slow and fraught.
